In [1]:
from mxnet import nd

### Scalars

In [2]:
x = nd.array([3.0])
y = nd.array([2.0])

print(x+y)
print(x*y)
print(x/y)
print(nd.power(x,y))


[ 5.]
<NDArray 1 @cpu(0)>

[ 6.]
<NDArray 1 @cpu(0)>

[ 1.5]
<NDArray 1 @cpu(0)>

[ 9.]
<NDArray 1 @cpu(0)>


In [5]:
x.asnumpy()
x.asscalar() # convert to python float

3.0

### Vectors

In [9]:
u = nd.arange(4)
print(u)
u[3]


[ 0.  1.  2.  3.]
<NDArray 4 @cpu(0)>



[ 3.]
<NDArray 1 @cpu(0)>

In [8]:
print(len(u))
print(u.shape)

4
(4,)


In [12]:
u.reshape((4,1))
u.shape

(4,)

### Matrices

In [16]:
A = nd.zeros((5,4))
print(A.shape)
A

(5, 4)



[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 5x4 @cpu(0)>

In [17]:
x = nd.arange(20)
A = x.reshape((5, 4))
A


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>

In [20]:
print(A[2,3])
print(A[2,:])
print(A[:,3])


[ 11.]
<NDArray 1 @cpu(0)>

[  8.   9.  10.  11.]
<NDArray 4 @cpu(0)>

[  3.   7.  11.  15.  19.]
<NDArray 5 @cpu(0)>


In [21]:
A.T


[[  0.   4.   8.  12.  16.]
 [  1.   5.   9.  13.  17.]
 [  2.   6.  10.  14.  18.]
 [  3.   7.  11.  15.  19.]]
<NDArray 4x5 @cpu(0)>

### Tensors

In [22]:
X = nd.arange(24).reshape((2,3,4))
print(X.shape)
print(X)

(2, 3, 4)

[[[  0.   1.   2.   3.]
  [  4.   5.   6.   7.]
  [  8.   9.  10.  11.]]

 [[ 12.  13.  14.  15.]
  [ 16.  17.  18.  19.]
  [ 20.  21.  22.  23.]]]
<NDArray 2x3x4 @cpu(0)>


### element-wise operation

In [25]:
u = nd.array([1,2,4,8])
v = nd.ones_like(u)*2
print(v)
print(u+v)
print(u-v)
print(u*v)
print(u/v)


[ 2.  2.  2.  2.]
<NDArray 4 @cpu(0)>

[  3.   4.   6.  10.]
<NDArray 4 @cpu(0)>

[-1.  0.  2.  6.]
<NDArray 4 @cpu(0)>

[  2.   4.   8.  16.]
<NDArray 4 @cpu(0)>

[ 0.5  1.   2.   4. ]
<NDArray 4 @cpu(0)>


In [28]:
B = nd.ones_like(A)*3
print(A)
print(B)
print(A+B)
print(A*B)


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>

[[ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]
 [ 3.  3.  3.  3.]]
<NDArray 5x4 @cpu(0)>

[[  3.   4.   5.   6.]
 [  7.   8.   9.  10.]
 [ 11.  12.  13.  14.]
 [ 15.  16.  17.  18.]
 [ 19.  20.  21.  22.]]
<NDArray 5x4 @cpu(0)>

[[  0.   3.   6.   9.]
 [ 12.  15.  18.  21.]
 [ 24.  27.  30.  33.]
 [ 36.  39.  42.  45.]
 [ 48.  51.  54.  57.]]
<NDArray 5x4 @cpu(0)>


### sums and means

In [34]:
print(u)
print(nd.sum(u))
u.sum()


[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>

[ 15.]
<NDArray 1 @cpu(0)>



[ 15.]
<NDArray 1 @cpu(0)>

In [36]:
print(A)
A.sum()


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]
 [ 12.  13.  14.  15.]
 [ 16.  17.  18.  19.]]
<NDArray 5x4 @cpu(0)>



[ 190.]
<NDArray 1 @cpu(0)>

In [42]:
print(nd.mean(A))
A.mean(axis = 1)


[ 9.5]
<NDArray 1 @cpu(0)>



[  1.5   5.5   9.5  13.5  17.5]
<NDArray 5 @cpu(0)>

### dot-product

In [52]:
# dot product -> weighted average
print(u)
print(v)
print(nd.dot(u,v))
nd.sum(u*v)


[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>

[ 2.  2.  2.  2.]
<NDArray 4 @cpu(0)>

[ 30.]
<NDArray 1 @cpu(0)>



[ 30.]
<NDArray 1 @cpu(0)>

In [55]:
nd.dot(A,u)


[  34.   94.  154.  214.  274.]
<NDArray 5 @cpu(0)>

In [58]:
print(A.shape)
print(u.shape)

(3, 4)
(4,)


In [61]:
A = nd.ones((3,4))
B = nd.ones((4,5))
print(nd.dot(A,B))
print(nd.dot(A,B).shape)


[[ 4.  4.  4.  4.  4.]
 [ 4.  4.  4.  4.  4.]
 [ 4.  4.  4.  4.  4.]]
<NDArray 3x5 @cpu(0)>
(3, 5)


### Norm

In [66]:
print(u)
print(nd.norm(u)) # L2 norm (euclidean dist.)
print(nd.sum(nd.abs(u))) # L1 norm

# the term norm is used to describe optimzation term like 'minimize' or 'maximize'


[ 1.  2.  4.  8.]
<NDArray 4 @cpu(0)>

[ 9.21954441]
<NDArray 1 @cpu(0)>

[ 15.]
<NDArray 1 @cpu(0)>
