### Basic operation

In [3]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)
import numpy as np

In [16]:
x = nd.empty((3,4))
x


[[  0.00000000e+00   0.00000000e+00   1.00303112e-28  -4.65661287e-10]
 [  6.31828438e-38   1.40129846e-45   3.05664674e-39   1.40129846e-45]
 [  3.05669158e-39   1.40129846e-45   0.00000000e+00   0.00000000e+00]]
<NDArray 3x4 @cpu(0)>

In [18]:
x = nd.zeros((3,4))
x


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
<NDArray 3x4 @cpu(0)>

In [28]:
x = nd.ones((3,4))
x


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [29]:
x.shape

(3, 4)

In [27]:
y = nd.random_normal(0,1, shape=(3,4))
y
print(y.shape)
print(y.size)

(3, 4)
12


In [30]:
x + y


[[-1.45050359  3.84679461 -0.49613762  1.70697188]
 [ 0.30285645  0.69026262  0.34935033 -0.23758733]
 [ 0.47777891  2.33765078  0.11382121  3.10640454]]
<NDArray 3x4 @cpu(0)>

In [35]:
x*y
# element-wise multiplication


[[-2.45050359  2.84679461 -1.49613762  0.70697188]
 [-0.69714355 -0.30973738 -0.65064967 -1.23758733]
 [-0.52222109  1.33765078 -0.88617879  2.10640454]]
<NDArray 3x4 @cpu(0)>

In [34]:
nd.exp(y)
# element


[[  0.08625014  17.23245621   0.22399364   2.02784133]
 [  0.49800581   0.7336396    0.52170676   0.29008326]
 [  0.59320152   3.8100822    0.41222796   8.21863842]]
<NDArray 3x4 @cpu(0)>

In [37]:
nd.dot(x,y.T)
# matrix-matrix product


[[-0.39287472 -2.895118    2.0356555 ]
 [-0.39287472 -2.895118    2.0356555 ]
 [-0.39287472 -2.895118    2.0356555 ]]
<NDArray 3x3 @cpu(0)>

### Inplace operation

In [43]:
print(id(y))
y = x+y
print(id(y)) # newly allocated memory reference

4572135552
4572135944


In [45]:
print(id(y))
y[:] = x+y
print(id(y))

4572135944
4572135944


In [49]:
# to avoid temporary memory buffer of x and y
nd.elemwise_add(x,y, out=y)
y


[[  6.54949665  11.84679413   7.50386238   9.70697212]
 [  8.30285645   8.69026279   8.34934998   7.76241255]
 [  8.47777939  10.3376503    8.11382103  11.1064043 ]]
<NDArray 3x4 @cpu(0)>

### Slicing

In [98]:
x = nd.arange(12).reshape(shape = (3,4))
x


[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
<NDArray 3x4 @cpu(0)>

In [99]:
x[1:3]


[[  4.   5.   6.   7.]
 [  8.   9.  10.  11.]]
<NDArray 2x4 @cpu(0)>

In [103]:
print(x[1])
print(x[1:2])


[ 4.  5.  6.  7.]
<NDArray 4 @cpu(0)>

[[ 4.  5.  6.  7.]]
<NDArray 1x4 @cpu(0)>


In [106]:
x[1:2,1:3]


[[ 5.  6.]]
<NDArray 1x2 @cpu(0)>

## Broadcasting

In [114]:
x = nd.ones((3,3))
print(x)
y = nd.arange(3) # shape (1,3)
print(y)
print(x + y)
y = y.reshape((3,1))
print(y)
print(x+y)


[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 3x3 @cpu(0)>

[ 0.  1.  2.]
<NDArray 3 @cpu(0)>

[[ 1.  2.  3.]
 [ 1.  2.  3.]
 [ 1.  2.  3.]]
<NDArray 3x3 @cpu(0)>

[[ 0.]
 [ 1.]
 [ 2.]]
<NDArray 3x1 @cpu(0)>

[[ 1.  1.  1.]
 [ 2.  2.  2.]
 [ 3.  3.  3.]]
<NDArray 3x3 @cpu(0)>


## convert from mxnet ndarray to numpy array

In [116]:
a = x.asnumpy()
type(a)
print(a)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


## managing context

In [117]:
z = nd.ones(shape=(3,3), ctx = mx.gpu(0))

MXNetError: [18:00:57] src/imperative/imperative.cc:78: Operator _ones is not implemented for GPU.

Stack trace returned 6 entries:
[bt] (0) 0   libmxnet.so                         0x000000010766d2b5 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x000000010877ee03 _ZN5mxnet10Imperative8InvokeOpERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_RKNS9_INS_9OpReqTypeENSC_ISH_EEEENS_12DispatchModeENS_10OpStatePtrE + 2099
[bt] (2) 2   libmxnet.so                         0x0000000108782b01 _ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_ + 865
[bt] (3) 3   libmxnet.so                         0x0000000108703e8e _Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_ + 382
[bt] (4) 4   libmxnet.so                         0x0000000108704ce4 MXImperativeInvokeEx + 164
[bt] (5) 5   _ctypes.so                          0x00000001064c2127 ffi_call_unix64 + 79


In [118]:
x_gpu = x.copyto(mx.gpu(0))

MXNetError: [18:01:52] src/ndarray/ndarray.cc:565: GPU is not enabled

Stack trace returned 9 entries:
[bt] (0) 0   libmxnet.so                         0x000000010766d2b5 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x0000000108859aa7 _ZN5mxnet10CopyFromToERKNS_7NDArrayES2_i + 1463
[bt] (2) 2   libmxnet.so                         0x00000001087915ad _ZZN5mxnet10imperative14PushFComputeExERKNSt3__18functionIFvRKN4nnvm9NodeAttrsERKNS_9OpContextERKNS1_6vectorINS_7NDArrayENS1_9allocatorISB_EEEERKNSA_INS_9OpReqTypeENSC_ISH_EEEESG_EEEPKNS3_2OpES6_RKNS_7ContextERKNSA_IPNS_6engine3VarENSC_ISY_EEEES12_RKNSA_INS_8ResourceENSC_IS13_EEEERKNSA_IPSB_NSC_IS18_EEEES1C_SL_ENKUlNS_10RunContextEE_clES1D_ + 253
[bt] (3) 3   libmxnet.so                         0x000000010877fd9f _ZN5mxnet10imperative14PushFComputeExERKNSt3__18functionIFvRKN4nnvm9NodeAttrsERKNS_9OpContextERKNS1_6vectorINS_7NDArrayENS1_9allocatorISB_EEEERKNSA_INS_9OpReqTypeENSC_ISH_EEEESG_EEEPKNS3_2OpES6_RKNS_7ContextERKNSA_IPNS_6engine3VarENSC_ISY_EEEES12_RKNSA_INS_8ResourceENSC_IS13_EEEERKNSA_IPSB_NSC_IS18_EEEES1C_SL_ + 1199
[bt] (4) 4   libmxnet.so                         0x000000010877e8f6 _ZN5mxnet10Imperative8InvokeOpERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_RKNS9_INS_9OpReqTypeENSC_ISH_EEEENS_12DispatchModeENS_10OpStatePtrE + 806
[bt] (5) 5   libmxnet.so                         0x0000000108782b01 _ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKNSt3__16vectorIPNS_7NDArrayENS8_9allocatorISB_EEEESG_ + 865
[bt] (6) 6   libmxnet.so                         0x0000000108703e8e _Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_ + 382
[bt] (7) 7   libmxnet.so                         0x0000000108704ce4 MXImperativeInvokeEx + 164
[bt] (8) 8   _ctypes.so                          0x00000001064c2127 ffi_call_unix64 + 79


In [119]:
x.context

cpu(0)

In [ ]:
## avoid allocte new memory when we do copyto of same context
print('id(z):', id(z))
z = z.copyto(mx.gpu(0))
print('id(z):', id(z))
z = z.as_in_context(mx.gpu(0))
print('id(z):', id(z))
print(z)